# Generated by Django 5.2 on 2025-04-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Palabra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(max_length=50)),
                ('nivel', models.CharField(choices=[('F', 'Fácil'), ('M', 'Medio'), ('D', 'Difícil')], max_length=1)),
                ('imagen', models.CharField(help_text='Nombre del archivo de imagen', max_length=100)),
                ('audio', models.CharField(help_text='Nombre del archivo de audio', max_length=100)),
            ],
        ),
    ]
