# Generated by Django 5.2 on 2025-04-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palabra',
            name='audio',
            field=models.FileField(upload_to='audios/'),
        ),
        migrations.AlterField(
            model_name='palabra',
            name='imagen',
            field=models.ImageField(upload_to='imagenes/'),
        ),
    ]
